services:
  dakosys:
    image: ghcr.io/sahara101/dakosys:latest
    container_name: dakosys
    volumes:
      - /home/rick/test/Dakosys/config:/app/config
      - /home/rick/test/Dakosys/data:/app/data
      - /kometa-config:/home/rick/Kometa/config
      - /home/rick/Kometa/config/overlays:/home/rick/Kometa/config/overlays
      - /home/rick/Kometa/config/collections:/home/rick/Kometa/config/collections
    command: --help
    stdin_open: true
    tty: true

  dakosys-updater:
    image: ghcr.io/sahara101/dakosys:latest
    container_name: dakosys-updater
    volumes:
      - /home/rick/test/Dakosys/config:/app/config
      - /home/rick/test/Dakosys/data:/app/data
      - /home/rick/Kometa/config:/kometa/config
    restart: unless-stopped
    command: daemon

